// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raiki02/EG/internal/cache"
	"github.com/raiki02/EG/internal/controller"
	"github.com/raiki02/EG/internal/dao"
	"github.com/raiki02/EG/internal/ioc"
	"github.com/raiki02/EG/internal/middleware"
	"github.com/raiki02/EG/internal/mq"
	"github.com/raiki02/EG/internal/router"
	"github.com/raiki02/EG/internal/server"
	"github.com/raiki02/EG/internal/service"
)

// Injectors from wire.go:

func InitApp() *server.Server {
	engine := ioc.InitGinHandler()
	db := ioc.InitDB()
	logger := ioc.Newlogger()
	userDao := dao.NewUserDao(db, logger)
	actDao := dao.NewActDao(db, logger)
	postDao := dao.NewPostDao(db, logger)
	commentDao := dao.NewCommentDao(db, logger)
	client := ioc.InitRedis()
	jwt := middleware.NewJwt(client)
	ccnuService := service.NewCCNUService()
	imgUploader := service.NewImgUploader()
	cacheCache := cache.NewCache(client)
	interactionDao := dao.NewInteractionDao(db, commentDao, userDao, actDao, postDao, logger)
	mqHdl := mq.NewMQ(client)
	auditorRepository := dao.NewAuditorRepo(db, logger)
	auditorService := service.NewAuditorService(auditorRepository, logger)
	activityService := service.NewActivityService(actDao, cacheCache, userDao, logger, interactionDao, mqHdl, auditorService)
	postService := service.NewPostService(postDao, userDao, logger, auditorService)
	userService := service.NewUserService(userDao, actDao, postDao, commentDao, jwt, ccnuService, imgUploader, activityService, postService, logger)
	userController := controller.NewUserController(engine, userService, logger)
	userRouter := router.NewUserRouter(engine, userController, jwt)
	actController := controller.NewActController(activityService, imgUploader, logger)
	actRouter := router.NewActRouter(engine, actController, jwt)
	postController := controller.NewPostController(postService, logger)
	postRouter := router.NewPostRouter(engine, postController, jwt)
	actPostCommentGetter := service.NewActPostCommentGetter(actDao, postDao, commentDao)
	commentService := service.NewCommentService(commentDao, userDao, interactionDao, logger, mqHdl, actPostCommentGetter)
	commentController := controller.NewCommentController(commentService, logger)
	commentRouter := router.NewCommentRouter(commentController, engine, jwt)
	feedDao := dao.NewFeedDao(db, logger)
	feedService := service.NewFeedService(feedDao, mqHdl, userDao, logger)
	feedController := controller.NewFeedController(feedService, logger)
	feedRouter := router.NewFeedRouter(feedController, engine, jwt)
	interactionService := service.NewInteractionService(interactionDao, mqHdl, logger, actPostCommentGetter)
	interactionController := controller.NewInteractionController(interactionService, logger)
	interactionRouter := router.NewInteractionRouter(engine, interactionController, jwt)
	cors := middleware.NewCors(engine)
	callbackAuditorService := service.NewCallbackAuditor(auditorRepository)
	callbackAuditorController := controller.NewCallbackAuditorController(engine, callbackAuditorService)
	routerRouter := router.NewRouter(engine, userRouter, actRouter, postRouter, commentRouter, feedRouter, interactionRouter, cors, callbackAuditorController)
	serverServer := server.NewServer(routerRouter, logger)
	return serverServer
}
